### ISSUE TITLE
Datasets and Research Questions

### ISSUE THREAD

**Issue by paradise1260** [UBC-MDS/DSCI_522_group09_Wine_Quality_Predictor#3]
Hello team,

Please provide 2 research questions and datasets under this issue.

**Comment by GloriaWYY** [comment]
[Glass Identification:](https://archive-beta.ics.uci.edu/ml/datasets/glass+identification)

- Classify the types of glasses (7 types of glasses) based on the refraction index, weight percentage in the corresponding oxide of sodium, magnesium, etc. 
- 10 features: all numerical
- shape: 214 rows by 11 columns
- Target with 10 classes
- Can do decision tree, SVC, logistic regression
![image](https://user-images.githubusercontent.com/89892646/142333472-f121cf45-f150-491e-8530-ec6ce7a4f6fb.png)
- Potential problem: a lot of 0's in the data set, is it the true value of the attribute or missing value?

[Diabetes prediction dataset](https://archive-beta.ics.uci.edu/ml/datasets/early+stage+diabetes+risk+prediction+dataset)
- Classify whether a patient has diabetes based on multiple indicators/symptoms such as age, gender, whether there is a sudden weight loss or not (yes/no).
- 16 features: age is numerical, the others are binary (gender, presence of a symptom)
- shape: 520 rows by 17 columns
- target is binary: positive/negative
- Can do decision tree, SVC, logistic regression
![image](https://user-images.githubusercontent.com/89892646/142333572-fc96fb30-8266-433b-aea7-ec4f3c7897e1.png)

**Comment by gfairbro** [comment]
[Wine Quality Classification](https://archive-beta.ics.uci.edu/ml/datasets/wine+quality):

Question: What features most affect a wine's quality rating?
We can use Logistic Regression and map out the coefficients that most affect the wine.
Or simply do an ML classification model, using any of the more advanced models we have learned.

Over 6000 examples, 12 features
target is multiclass
:
![image](https://user-images.githubusercontent.com/88786321/142338017-9d1382bf-fb32-4379-9a25-e18a960e39c1.png)

**Comment by gfairbro** [comment]
[Stock Performance projection:](https://archive-beta.ics.uci.edu/ml/datasets/dow+jones+index)

Question: Predict which stocks will have the highest rate of return the following week based on features and performance from the week prior. Alternatively we can also discuss which indicators are most likely to affect a positive performance in the following week. This is a regression problem not a classification problem.

750 examples, 16 features. 
![image](https://user-images.githubusercontent.com/88786321/142339053-b6acd8b5-d5f3-47a3-9e49-395c1c127b73.png)

**Comment by paradise1260** [comment]
[Online shoppers purchasing intention](https://archive-beta.ics.uci.edu/ml/datasets/online+shoppers+purchasing+intention+dataset)

Question: Predict whether an online shopper will end up shopping or not.

The dataset has 12330 examples and 17 features. The task is classification.
 
<img width="1393" alt="Screen Shot 2021-11-17 at 7 15 08 PM" src="https://user-images.githubusercontent.com/70858612/142345865-93b006e9-f953-474a-b3f1-6a799df85e5a.png">

[Defaulting credit cards](https://archive-beta.ics.uci.edu/ml/datasets/default+of+credit+card+clients)

Question: Predict whether a client will default their credit card or not.

The dataset has 30000 examples and 23 features. The task is classification.

<img width="1385" alt="Screen Shot 2021-11-17 at 7 24 45 PM" src="https://user-images.githubusercontent.com/70858612/142346308-0c2307b6-9a3d-4e01-b963-c0d7ddd6bde9.png">

**Comment by Luming-ubc** [comment]
I have found two suitable datasets.
Reasons: Both of the dataset are relatively clean and easy to work with. The description pages linked above are worth reading (very clear and straight to the point). Data.info() provides insights of the raw dataset.

1. Predict Student performance (Regression problem) https://archive-beta.ics.uci.edu/ml/datasets/student+performance
data.info()
RangeIndex: 649 entries, 0 to 648
Data columns (total 33 columns):
    Column      Non-Null Count  Dtype 
 0   school      649 non-null    object
 1   sex         649 non-null    object
 2   age         649 non-null    int64 
 3   address     649 non-null    object
 4   famsize     649 non-null    object
 5   Pstatus     649 non-null    object
 6   Medu        649 non-null    int64 
 7   Fedu        649 non-null    int64 
 8   Mjob        649 non-null    object
 9   Fjob        649 non-null    object
 10  reason      649 non-null    object
 11  guardian    649 non-null    object
 12  traveltime  649 non-null    int64 
 13  studytime   649 non-null    int64 
 14  failures    649 non-null    int64 
 15  schoolsup   649 non-null    object
 16  famsup      649 non-null    object
 17  paid        649 non-null    object
 18  activities  649 non-null    object
 19  nursery     649 non-null    object
 20  higher      649 non-null    object
 21  internet    649 non-null    object
 22  romantic    649 non-null    object
 23  famrel      649 non-null    int64 
 24  freetime    649 non-null    int64 
 25  goout       649 non-null    int64 
 26  Dalc        649 non-null    int64 
 27  Walc        649 non-null    int64 
 28  health      649 non-null    int64 
 29  absences    649 non-null    int64 
 30  G1          649 non-null    int64 
 31  G2          649 non-null    int64 
 32  G3          649 non-null    int64 
dtypes: int64(16), object(17)
memory usage: 167.4+ KB

2. Classify origin of wines (Classification problem) https://archive-beta.ics.uci.edu/ml/datasets/wine
Use 13 features to classify one of three origins; 178 entries
1) Alcohol 2) Malic acid 3) Ash 4) Alcalinity of ash 5) Magnesium 6) Total phenols 7) Flavanoids 8) Nonflavanoid phenols 9) Proanthocyanins 10)Color intensity 11)Hue 12)OD280/OD315 of diluted wines 13)Proline

Notes: I also think the wine quality dataset is interesting (Regression problem). https://archive-beta.ics.uci.edu/ml/datasets/wine+quality
RangeIndex: 1599 entries, 0 to 1598
Data columns (total 12 columns):
 Column                Non-Null Count  Dtype  
 0   fixed acidity         1599 non-null   float64
 1   volatile acidity      1599 non-null   float64
 2   citric acid           1599 non-null   float64
 3   residual sugar        1599 non-null   float64
 4   chlorides             1599 non-null   float64
 5   free sulfur dioxide   1599 non-null   float64
 6   total sulfur dioxide  1599 non-null   float64
 7   density               1599 non-null   float64
 8   pH                    1599 non-null   float64
 9   sulphates             1599 non-null   float64
 10  alcohol               1599 non-null   float64
 11  quality               1599 non-null   int64  
dtypes: float64(11), int64(1)
memory usage: 150.0 KB

I was thinking including both two datasets to form some research idea, since they are very close, just in case we are short of work to do. We could also just take one. :)

**Comment by gfairbro** [comment]
Here are my top 4:

1. Wine Quality
2. Diabetes
3. Stock Prediction
4. CC Default

**Comment by Luming-ubc** [comment]
My top 4:
1. Wine quality (interesting to me, preferred)
2. Others (also good datasets and doable): Default credit card, diabetes, student performance

**Comment by GloriaWYY** [comment]
My top 4:

1. Online shopping
2. Wine quality
3. Credit cards
4. Diabetes

All the datasets we chose seem very interesting, but I am thinking that a larger data set might be better, so here comes my ranking.

**Comment by paradise1260** [comment]
My top 4:
1. Wine quality
2. Online shopping
3. Student performance
3. Diabetes

**Comment by gfairbro** [comment]
Looks like we have a winner! I Love me some wine... 👍 

My follow up for the formal question:
Predict a wine's quality based on a set of chemical composition features

Possible stretch questions:
1. What are the top contributing features to a high quality wine?
2. Combining a second dataset, can we determine a probability that a wine came from 3 regions from the Classify origin of wines dataset

**Comment by Luming-ubc** [comment]
Add possible repo rename: 
Wine Quality Predictor
